# Generated by Django 2.1.2 on 2018-11-17 13:09

from django.conf import settings
import django.contrib.auth.mixins
from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.base


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0003_delete_some'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveGroup',
            fields=[
                ('groupmember_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groups.GroupMember')),
            ],
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, django.views.generic.base.RedirectView, 'groups.groupmember'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='groups.GroupMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='group',
            name='description_html',
        ),
        migrations.AddField(
            model_name='group',
            name='description_html',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
